import type { Metadata } from 'next';
import Script from 'next/script';
import './globals.css';
import '@rainbow-me/rainbowkit/styles.css';
import Navbar from '@/components/layouts/Navbar';

import Providers from './providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <link
          href='https://cdn.jsdelivr.net/npm/flowbite@2.4.1/dist/flowbite.min.css'
          rel='stylesheet'
        />
      </head>
      <body>
        <Providers>
          <Navbar />
          {children}
        </Providers>
        <Script src='https://cdn.jsdelivr.net/npm/flowbite@2.4.1/dist/flowbite.min.js'></Script>
      </body>
    </html>
  );
}
